plugins {
    id 'fabric-loom' version '1.18.3'
    id 'java'
}

group = 'app.enderlab'
version = '1.0.0'

base {
    archivesName = 'new-mod'
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'com.mojang:minecraft:26.2'
    mappings loom.officialMojangMappings()
    modImplementation 'net.fabricmc:fabric-loader:0.19.5'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.161.0+26.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}
